"""Pairwise indistinguishability (PRD 9.5 headline metric).

Design choices from the LLM-as-judge literature:
- Every pair is judged twice with positions swapped (MT-Bench-style position-bias
  control). Consistent picks count 1/0; inconsistent picks count 0.5 (uncertain).
- Judge runs at temperature 0 with a strict JSON contract.
- Accuracy is weighted by reconstruction_quality (PRD 9.2) and traces below
  0.2 are excluded from pairwise entirely.
- CI via seeded percentile bootstrap over pairs (Chatbot Arena practice).
- Position-bias and length-bias diagnostics are reported alongside the score.
"""

from __future__ import annotations

import random

from pydantic import BaseModel

from ..models import Trace
from .lm import LM, extract_json, pmap
from .stats import bootstrap_ci, clamp, weighted_mean

MIN_PAIRWISE_QUALITY = 0.2

JUDGE_SYSTEM = (
    "You are a forensic evaluator. One of the two candidate texts below was really "
    "written by the person; the other was generated by an AI simulating them. "
    "Judge only authorship signal: voice, judgment, specificity, taste. Ignore "
    "length and polish unless they are authorship evidence themselves. "
    'Respond with JSON only: {"real": "A" | "B", "confidence": <0.0-1.0>, '
    '"reason": "<one sentence>"}'
)


class PairResult(BaseModel):
    trace_id: str
    correct: float  # 1.0 both orders right, 0.5 inconsistent, 0.0 both wrong
    weight: float
    confidence: float
    first_position_pick_real_first: bool
    real_len: int
    generated_len: int


class PairwiseResult(BaseModel):
    n_pairs: int
    judge_accuracy: float
    score: float
    ci95: tuple[float, float]
    position_bias: float
    mean_real_len: float
    mean_generated_len: float
    pairs: list[PairResult]


def _judge_prompt(context: str, kind: str, a: str, b: str) -> str:
    ctx = context if context else "(no context; standalone artifact)"
    return (
        f"Artifact kind: {kind}\n\nContext:\n{ctx}\n\n"
        f"Candidate A:\n{a}\n\nCandidate B:\n{b}\n\n"
        "Which candidate was really written by the person? JSON only."
    )


def _judge_once(judge: LM, trace: Trace, first: str, second: str) -> tuple[str, float]:
    raw = judge.complete(
        JUDGE_SYSTEM, _judge_prompt(trace.context.content, trace.kind, first, second)
    )
    parsed = extract_json(raw)
    pick = str(parsed.get("real", "")).strip().upper()
    if pick not in ("A", "B"):
        raise ValueError(f"judge returned invalid pick: {parsed!r}")
    confidence = clamp(float(parsed.get("confidence", 0.5)))
    return pick, confidence


def judge_pair(judge: LM, trace: Trace, generated: str) -> PairResult:
    real = trace.behavior.content
    # Order 1: real is A. Order 2: real is B.
    pick1, conf1 = _judge_once(judge, trace, real, generated)
    pick2, conf2 = _judge_once(judge, trace, generated, real)
    correct1 = pick1 == "A"
    correct2 = pick2 == "B"
    correct = (float(correct1) + float(correct2)) / 2
    return PairResult(
        trace_id=trace.id,
        correct=correct,
        weight=trace.context.reconstruction_quality,
        confidence=(conf1 + conf2) / 2,
        first_position_pick_real_first=correct1,
        real_len=len(real),
        generated_len=len(generated),
    )


def eligible_pairwise_traces(traces: list[Trace], split: str = "test") -> list[Trace]:
    return [
        t
        for t in traces
        if t.split == split and t.context.reconstruction_quality >= MIN_PAIRWISE_QUALITY
    ]


def run_pairwise(
    judge: LM,
    traces: list[Trace],
    generations: dict[str, str],
    n_pairs: int | None = None,
    seed: int = 0,
    concurrency: int = 1,
) -> PairwiseResult:
    """Judge (real, generated) pairs for traces with generations available."""
    pool = [t for t in traces if t.id in generations]
    rng = random.Random(seed)
    if n_pairs is not None and len(pool) > n_pairs:
        pool = rng.sample(pool, n_pairs)
    results = pmap(
        lambda t: judge_pair(judge, t, generations[t.id]), pool, max_workers=concurrency
    )
    if not results:
        return PairwiseResult(
            n_pairs=0,
            judge_accuracy=0.0,
            score=0.0,
            ci95=(0.0, 0.0),
            position_bias=0.0,
            mean_real_len=0.0,
            mean_generated_len=0.0,
            pairs=[],
        )
    values = [r.correct for r in results]
    weights = [r.weight for r in results]
    accuracy = weighted_mean(values, weights)

    def stat(v, w):
        return clamp(2 * (1 - weighted_mean(v, w)))

    ci = bootstrap_ci(values, weights, stat, seed=seed)
    acc_real_first = sum(1 for r in results if r.first_position_pick_real_first) / len(results)
    # Second order: correct2 = 2*correct - correct1
    acc_real_second = sum(
        (2 * r.correct - float(r.first_position_pick_real_first)) for r in results
    ) / len(results)
    return PairwiseResult(
        n_pairs=len(results),
        judge_accuracy=round(accuracy, 4),
        score=round(clamp(2 * (1 - accuracy)), 4),
        ci95=ci,
        position_bias=round(abs(acc_real_first - acc_real_second), 4),
        mean_real_len=round(sum(r.real_len for r in results) / len(results), 1),
        mean_generated_len=round(sum(r.generated_len for r in results) / len(results), 1),
        pairs=results,
    )
